version: '3.0'
services:
    api:
        image: api:0.0.1
        container_name: api
        build: 
            context: api/
            dockerfile: Dockerfile-api
        ports:
            - "3333:3333"
        environment:
            - PORT=3333
        volumes:
            - ./api/db.json:/api/db.json
    locust:
        image: locustio/locust
        ports:
            - "8089:8089"
        volumes:
            - ./load_tests/:/mnt/locust
        command: -f /mnt/locust/locustfile.py
        depends_on:
            - api
    locust-metrics-exporter:
        image: containersol/locust_exporter
        ports:
            - "9646:9646"
        environment:
            - LOCUST_EXPORTER_URI=http://locust:8089
        depends_on:
            - locust
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - 9090:9090
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - api
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - ./grafana.ini:/etc/grafana/grafana.ini
            - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
        # links:
        #     - prometheus