{
 "title": "API Performance vs Resource",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Locust RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "locust_requests_current_rps" }
   ]
  },
  {
   "title": "Locust AVG resp time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "locust_requests_avg_response_time"
    }
   ]
  },
  {
   "title": "API MEM usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"api\"}"
    }
   ]
  },
  {
   "title": "API CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"api\"}[1m]))"
    }
   ]
  }
 ]
}